from typing import Protocol

from app.domain.models import AgentDecision, ParsedInboundMessage


class VendorRepository(Protocol):
    async def get_by_id(self, vendor_id: int) -> dict | None: ...
    async def get_by_email(self, email: str) -> dict | None: ...
    async def get_by_pending_email(self, email: str) -> dict | None: ...
    async def get_by_google_subject_id(self, subject_id: str) -> dict | None: ...
    async def get_by_instagram_user_id(self, user_id: str) -> dict | None: ...
    async def get_password_hash(self, email: str) -> str | None: ...
    async def get_password_hash_by_id(self, vendor_id: int) -> str | None: ...
    async def get_by_phone_number_id(self, phone_number_id: str) -> dict | None: ...
    async def get_by_instagram_page_id(self, page_id: str) -> dict | None: ...
    async def get_by_telegram_vendor_chat_id(self, chat_id: str) -> dict | None: ...
    async def get_by_telegram_customer_chat_id(self, chat_id: str) -> dict | None: ...
    async def create_vendor(self, name: str, email: str, password_hash: str) -> dict: ...
    async def update_password_hash(self, vendor_id: int, password_hash: str) -> bool: ...
    async def set_email_verified(self, vendor_id: int) -> dict | None: ...
    async def set_pending_email(self, vendor_id: int, email: str | None) -> dict | None: ...
    async def apply_pending_email(self, vendor_id: int, email: str) -> dict | None: ...
    async def update_profile(self, vendor_id: int, payload: dict) -> dict | None: ...
    async def link_google_subject(self, vendor_id: int, subject_id: str, mark_email_verified: bool = False) -> dict | None: ...
    async def link_instagram_user(self, vendor_id: int, user_id: str) -> dict | None: ...
    async def update_catalogue(self, vendor_id: int, payload: dict) -> dict | None: ...
    async def update_whatsapp_credentials(
        self,
        vendor_id: int,
        whatsapp_number: str | None = None,
        whatsapp_token: str | None = None,
        whatsapp_phone_number_id: str | None = None,
    ) -> dict | None: ...
    async def update_instagram_credentials(self, vendor_id: int, page_id: str, page_token: str) -> dict | None: ...
    async def update_telegram_credentials(self, vendor_id: int, bot_token: str | None = None, vendor_chat_id: str | None = None) -> dict | None: ...


class EmailVerificationRepository(Protocol):
    async def create_token(self, vendor_id: int, token_hash: str, purpose: str, email: str, expires_at) -> dict: ...
    async def consume_token(self, token_hash: str, purpose: str) -> dict | None: ...


class ProductRepository(Protocol):
    async def list_for_vendor(
        self,
        vendor_id: int,
        *,
        limit: int = 50,
        offset: int = 0,
        in_stock: bool | None = None,
        search: str | None = None,
    ) -> list[dict]: ...
    async def get_for_vendor(self, vendor_id: int, product_id: int) -> dict | None: ...
    async def create_for_vendor(self, vendor_id: int, payload: dict) -> dict: ...
    async def update_for_vendor(self, vendor_id: int, product_id: int, payload: dict) -> dict | None: ...
    async def delete_for_vendor(self, vendor_id: int, product_id: int) -> bool: ...


class CatalogueRepository(Protocol):
    async def create_upload(self, vendor_id: int, payload: dict) -> dict: ...
    async def get_upload_for_vendor(self, vendor_id: int, upload_id: int) -> dict | None: ...
    async def list_uploads_for_vendor(self, vendor_id: int) -> list[dict]: ...
    async def mark_upload_processed(self, vendor_id: int, upload_id: int, extracted_text: str, item_payloads: list[dict]) -> dict | None: ...
    async def mark_upload_failed(self, vendor_id: int, upload_id: int, error_message: str) -> dict | None: ...
    async def list_items_for_upload(self, vendor_id: int, upload_id: int) -> list[dict]: ...
    async def import_item_as_product(self, vendor_id: int, item_id: int) -> dict | None: ...
    async def import_items_as_products(self, vendor_id: int, item_payloads: list[dict]) -> list[dict]: ...


class CustomerRepository(Protocol):
    async def get_or_create_by_whatsapp(self, whatsapp_number: str, display_name: str | None = None) -> dict: ...
    async def get_or_create_by_instagram(self, instagram_id: str, display_name: str | None = None) -> dict: ...
    async def get_or_create_by_telegram(self, telegram_id: str, chat_id: str, display_name: str | None = None) -> dict: ...
    async def upsert_vendor_customer(self, vendor_id: int, customer_id: int) -> None: ...
    async def upsert_conversation_state(self, vendor_id: int, customer_id: int, last_message: str | None) -> None: ...
    async def record_message(
        self,
        *,
        vendor_id: int,
        customer_id: int,
        direction: str,
        message_type: str,
        body_text: str | None,
        whatsapp_message_id: str | None = None,
        sender_number: str | None = None,
        recipient_number: str | None = None,
    ) -> None: ...
    async def upsert_order_lifecycle_state(
        self,
        *,
        vendor_id: int,
        customer_id: int,
        status: str,
        last_event_text: str | None,
    ) -> None: ...
    async def get_order_lifecycle_state(self, *, vendor_id: int, customer_id: int) -> dict | None: ...
    async def get_google_contact_saved(self, *, vendor_id: int, customer_id: int) -> bool: ...
    async def set_google_contact_saved(self, *, vendor_id: int, customer_id: int, saved: bool = True) -> None: ...
    async def list_messages(self, vendor_id: int, customer_id: int, limit: int = 10) -> list[dict]: ...


class VendorSettingsRepository(Protocol):
    async def get(self, vendor_id: int) -> dict: ...
    async def upsert(self, vendor_id: int, payload: dict) -> dict: ...


class BusinessInfoRepository(Protocol):
    async def list_for_vendor(self, vendor_id: int) -> list[dict]: ...
    async def create_for_vendor(self, vendor_id: int, payload: dict) -> dict: ...
    async def delete_for_vendor(self, vendor_id: int, info_id: int) -> bool: ...
    async def search(self, vendor_id: int, query: str) -> str | None: ...


class ContactsAdapter(Protocol):
    async def save_if_new(self, vendor_id: int, display_name: str, whatsapp_number: str) -> bool: ...


class GoogleTokenRepository(Protocol):
    async def get_token_json(self, vendor_id: int) -> str | None: ...
    async def upsert_token_json(self, vendor_id: int, token_json: str) -> None: ...
    async def delete_for_vendor(self, vendor_id: int) -> bool: ...


class GoogleSheetsTokenRepository(Protocol):
    async def get_token_json(self, vendor_id: int) -> str | None: ...
    async def upsert_token_json(self, vendor_id: int, token_json: str) -> None: ...
    async def delete_for_vendor(self, vendor_id: int) -> bool: ...


class OrderRepository(Protocol):
    async def create_order(self, vendor_id: int, payload: dict) -> dict: ...
    async def get_for_vendor(self, vendor_id: int, order_id: int) -> dict | None: ...
    async def mark_synced(self, order_id: int) -> None: ...
    async def record_sync_failure(self, order_id: int, error: str, retry_delay_seconds: int) -> None: ...
    async def claim_pending(self, limit: int = 50) -> list[dict]: ...
    async def list_pending_for_vendor(self, vendor_id: int) -> list[dict]: ...
    async def count_for_vendor(self, vendor_id: int, synced: bool) -> int: ...


class WhatsAppAdapter(Protocol):
    async def send_text(self, vendor: dict, to: str, body: str) -> None: ...
    async def send_buttons(self, vendor: dict, to: str, body: str, buttons: list[dict]) -> None: ...


class InstagramAdapter(Protocol):
    async def send_text(self, vendor: dict, to: str, body: str) -> None: ...
    async def send_quick_replies(self, vendor: dict, to: str, body: str, replies: list[dict]) -> None: ...


class TelegramAdapter(Protocol):
    async def send_text(self, vendor: dict, to: str, body: str) -> None: ...


class AgentOrchestrator(Protocol):
    async def decide(self, vendor: dict, message: ParsedInboundMessage, is_vendor_sender: bool) -> AgentDecision: ...
