"""Add Instagram support

Revision ID: 4c8489f771cb
Revises: 20260420_02
Create Date: 2026-05-06 19:16:20.062461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c8489f771cb'
down_revision: Union[str, None] = '20260420_02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_business_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), server_default=sa.text("'TEXT'"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_business_info_vendor_id'), 'vendor_business_info', ['vendor_id'], unique=False)
    op.alter_column('conversation_states', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.add_column('customers', sa.Column('instagram_id', sa.String(length=100), nullable=True))
    op.alter_column('customers', 'whatsapp_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.create_unique_constraint(None, 'customers', ['instagram_id'])
    op.alter_column('messages', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('order_lifecycle_states', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('vendor_bot_settings', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('vendor_customers', 'first_seen_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('vendor_customers', 'last_seen_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('vendor_google_tokens', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.add_column('vendors', sa.Column('instagram_account_id', sa.String(length=100), nullable=True))
    op.add_column('vendors', sa.Column('facebook_page_token', sa.Text(), nullable=True))
    op.alter_column('vendors', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_unique_constraint(None, 'vendors', ['instagram_account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='unique')
    op.alter_column('vendors', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.drop_column('vendors', 'facebook_page_token')
    op.drop_column('vendors', 'instagram_account_id')
    op.alter_column('vendor_google_tokens', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('vendor_customers', 'last_seen_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('vendor_customers', 'first_seen_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('vendor_bot_settings', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('order_lifecycle_states', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.drop_constraint(None, 'customers', type_='unique')
    op.alter_column('customers', 'whatsapp_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('customers', 'instagram_id')
    op.alter_column('conversation_states', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.drop_index(op.f('ix_vendor_business_info_vendor_id'), table_name='vendor_business_info')
    op.drop_table('vendor_business_info')
    # ### end Alembic commands ###
